# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.1'

    - name: Test
      run: go test -cover -v ./...

    - name: Build
      run: go build -v ./...

  deploy:
    runs-on: ubuntu-latest
    environment: testing
    steps:

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
        role-session-name: testing-session
        aws-region: ${{ vars.AWS_REGION }}
